src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Home_Country__c</fullName>
        <label>Home Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Home_Country__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Product</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Country_Descriptor__mdt.object
<CustomObject>
    <fields>
        <fullName>Currency_Code__c</fullName>
        <label>Currency Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>EUR</fullName>
                    <default>true</default>
                    <label>EUR</label>
                </value>
                <value>
                    <fullName>GBP</fullName>
                </value>
                <value>
                    <fullName>USD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Country Descriptor</label>
    <pluralLabel>Country Descriptors</pluralLabel>
</CustomObject>

src/objects/Product_Option__c.object
<CustomObject>
    <fields>
        <fullName>Currency_Value__c</fullName>
        <label>Currency Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Option_Type__c</fullName>
        <label>Option Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Currency</fullName>
                </value>
                <value>
                    <fullName>Percent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Percent_Value__c</fullName>
        <label>Percent Value</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product Options</relationshipLabel>
        <relationshipName>Product_Options</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Option</label>
    <nameField>
        <label>Product Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CreateNewProductController.cls
public with sharing class CreateNewProductController {
    public static final String DEFAULT_CURRENCY = 'EUR';
    public static final String PRODUCT_FAMILY = 'Account';

    private static List<ProductDescriptor> PRODUCT_OPTION_DESCRIPTORS {
        get {
            if (PRODUCT_OPTION_DESCRIPTORS == null) {
                PRODUCT_OPTION_DESCRIPTORS = ProductDescriptor.getProductDescriptors();
            }
            return PRODUCT_OPTION_DESCRIPTORS;
        }
        set;
    }

    public class PicklistOption {
        @AuraEnabled
        public String label { get; set; }
        @AuraEnabled
        public String value { get; set; }

        public PicklistOption(String lbl, String val) {
            label = lbl;
            value = val;
        }
    }

    @AuraEnabled(Cacheable=true)
    public static Map<String, Object> getInitialData() {
        Map<String, Object> result = new Map<String, Object>();

        result.put('countries', getCountryList());
        result.put('defaultCurrency', DEFAULT_CURRENCY);
        result.put('prodOptionDescriptors', ProductDescriptor.getProductDescriptors());
        result.put('currencyByCountry', getCurrencyByCountry());

        return result;
    }

    @AuraEnabled
    public static void createProducts(String productName, List<Map<String, Object>> products) {
        Product2 productTemplate = new Product2(
                Name = productName,
                Family = PRODUCT_FAMILY
        );

        List<Cascade> cascades = new List<Cascade>();

        for (Map<String, Object> product : products) {
            Product2 parentProduct = productTemplate.clone();

            parentProduct.ProductCode = productName + '-' + (product.containsKey('country') ? String.valueOf(product.get('country')) : '');
            parentProduct.IsActive = product.containsKey('isActive') ? Boolean.valueOf(product.get('isActive')) : true; // true - default value
            parentProduct.CurrencyIsoCode = product.containsKey('currencyCode') ? String.valueOf(product.get('currencyCode')) : DEFAULT_CURRENCY;

            Cascade cscd = new Cascade(parentProduct, 'Product__c', generateProductOptions(product));

            cascades.add(cscd);
        }

        Cascade.cascadeInsert(cascades);
    }

    private static List<PicklistOption> getCountryList() {
        List<PicklistOption> result = new List<PicklistOption>();
        for (PicklistEntry pe : Contact.Home_Country__c.getDescribe().getPicklistValues()) {
            if (pe.active) {
                result.add(new PicklistOption(pe.label, pe.value));
            }
        }
        return result;
    }

    private static Map<String, String> getCurrencyByCountry() {
        Map<String, String> result = new Map<String, String>();
        for (Country_Descriptor__mdt cd : CountryDescriptorSelector.getCountryDescriptors()) {
            result.put(cd.Label, cd.Currency_Code__c);
        }
        return result;
    }

    private static List<Product_Option__c> generateProductOptions(Map<String, Object> product) {
        List<Product_Option__c> result = new List<Product_Option__c>();

        for (ProductDescriptor pd : PRODUCT_OPTION_DESCRIPTORS) {
            if (product.containsKey(pd.productOptionName)) {

                Product_Option__c newProductOption = new Product_Option__c(
                        Name = pd.productOptionLabel,
                        Option_Type__c = pd.optionType
                );

                newProductOption.CurrencyIsoCode = CountryDescriptorSelector.CURRENCY_BY_COUNTRY.get((String)product.get('country'));

                if (product.containsKey(pd.productOptionName) && product.get(pd.productOptionName) != null) {
                    switch on pd.optionType {
                        when 'Currency' {
                            System.debug(pd.productOptionName);
                            newProductOption.Currency_Value__c = Decimal.valueOf((String)product.get(pd.productOptionName));
                        }
                        when 'Percent' {
                            newProductOption.Percent_Value__c = Decimal.valueOf((String)product.get(pd.productOptionName));
                        }
                    }
                }

                result.add(
                        newProductOption
                );
            }
        }

        return result;
    }
}