src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Home_Country__c</fullName>
        <label>Home Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Lookup</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Home_Country__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Product</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ContactTriggerHandler.cls
public with sharing class ContactTriggerHandler {
    public void onBeforeInsert(List<Contact> newList) {
        assignProduct(newList);
    }

    public void onBeforeUpdate(List<Contact> newList, Map<Id, Contact> oldMap) {
        assignProduct(newList);
    }

    private void assignProduct(List<Contact> newList) {
        for (Contact con : newList) {
            if (ProductSelector.PRODUCT_BY_PRODUCT_CODE.containsKey(con.Product__c + '-' + con.Home_Country__c)) {
                con.Product_Lookup__c = ProductSelector.PRODUCT_BY_PRODUCT_CODE.get(con.Product__c + '-' + con.Home_Country__c).Id;
            }
        }
    }
}