src/objects/Country_Descriptor__mdt.object
<CustomObject>
    <fields>
        <fullName>Currency_Code__c</fullName>
        <label>Currency Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>EUR</fullName>
                    <default>true</default>
                    <label>EUR</label>
                </value>
                <value>
                    <fullName>GBP</fullName>
                </value>
                <value>
                    <fullName>USD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Country Descriptor</label>
    <pluralLabel>Country Descriptors</pluralLabel>
</CustomObject>

src/classes/CountryDescriptorSelector.cls
/**
 * Selector class for Country_Descriptor__mdt (Custom Metadata Type)
 */
public inherited sharing class CountryDescriptorSelector {
    /**
     * @description get all Country_Descriptor__mdt records
     * @return list of country descriptors
     */
    public static List<Country_Descriptor__mdt> getCountryDescriptors() {
        return [SELECT Label, DeveloperName, Currency_Code__c FROM Country_Descriptor__mdt];
    }

    /**
     * @description cached map which contains countries as keys and currencies as values
     */
    public static Map<String, String> CURRENCY_BY_COUNTRY {
        get {
            if (CURRENCY_BY_COUNTRY == null) {
                Map<String, String> result = new Map<String, String>();

                for (Country_Descriptor__mdt cd : getCountryDescriptors()) {
                    result.put(cd.DeveloperName, cd.Currency_Code__c);
                }

                CURRENCY_BY_COUNTRY = result;
            }
            return CURRENCY_BY_COUNTRY;
        }

        set;
    }
}