src/objects/Product_Option_Descriptor__mdt.object
<CustomObject>
    <fields>
        <fullName>Is_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Label_instead_of_NULL__c</fullName>
        <label>Label instead of NULL</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Option_Type__c</fullName>
        <label>Option Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Currency</fullName>
                    <default>true</default>
                    <label>Currency</label>
                </value>
                <value>
                    <fullName>Percent</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product Option Descriptor</label>
    <pluralLabel>Product Option Descriptors</pluralLabel>
</CustomObject>

src/classes/ProductDescriptor.cls
public with sharing class ProductDescriptor {
    @AuraEnabled
    public String productOptionLabel { get; set; }
    @AuraEnabled
    public String productOptionName { get; set; }
    @AuraEnabled
    public String labelInsteadOfNull { get; set; }
    @AuraEnabled
    public String optionType { get; set; }
    @AuraEnabled
    public Boolean isRequired { get; set; }

    public ProductDescriptor(Product_Option_Descriptor__mdt productOptionDescriptor) {
        this.productOptionLabel = productOptionDescriptor.Label;
        this.productOptionName = productOptionDescriptor.DeveloperName;
        this.labelInsteadOfNull = productOptionDescriptor.Label_instead_of_NULL__c;
        this.optionType = productOptionDescriptor.Option_Type__c;
        this.isRequired = productOptionDescriptor.Is_Required__c;
    }

    public static List<ProductDescriptor> getProductDescriptors() {
        List<ProductDescriptor> result = new List<ProductDescriptor>();
        for (Product_Option_Descriptor__mdt pd : ProductOptionDescriptorSelector.getDescriptors()) {
            result.add(new ProductDescriptor(pd));
        }
        return result;
    }
}