src/objects/Product_Option_Descriptor__mdt.object
<CustomObject>
    <fields>
        <fullName>Is_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Label_instead_of_NULL__c</fullName>
        <label>Label instead of NULL</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Option_Type__c</fullName>
        <label>Option Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Currency</fullName>
                    <default>true</default>
                    <label>Currency</label>
                </value>
                <value>
                    <fullName>Percent</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product Option Descriptor</label>
    <pluralLabel>Product Option Descriptors</pluralLabel>
</CustomObject>

src/classes/ProductOptionDescriptorSelector.cls
/**
 * Selector class for Product_Option_Descriptor__mdt (Custom Metadata Type)
 */
public inherited sharing class ProductOptionDescriptorSelector {
    // get list of all Product_Option_Descriptor__mdt records
    public static List<Product_Option_Descriptor__mdt> getDescriptors() {
        return [SELECT Id, Label, DeveloperName, Option_Type__c,
                Label_instead_of_NULL__c, Is_Required__c FROM Product_Option_Descriptor__mdt];
    }
}