src/objects/Product_Option__c.object
<CustomObject>
    <fields>
        <fullName>Currency_Value__c</fullName>
        <label>Currency Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Option_Type__c</fullName>
        <label>Option Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Currency</fullName>
                </value>
                <value>
                    <fullName>Percent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Percent_Value__c</fullName>
        <label>Percent Value</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product Options</relationshipLabel>
        <relationshipName>Product_Options</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Option</label>
    <nameField>
        <label>Product Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProductSelector.cls
public with sharing class ProductSelector {
    public static Map<String, Product2> PRODUCT_BY_PRODUCT_CODE {
        get {
            if (PRODUCT_BY_PRODUCT_CODE == null) {
                Map<String, Product2> result = new Map<String, Product2>();

                for (Product2 product : getAccountProducts()) {
                    result.put(product.ProductCode, product);
                }

                PRODUCT_BY_PRODUCT_CODE = result;
            }
            return PRODUCT_BY_PRODUCT_CODE;
        }
        set;
    }

    public static List<Product2> getAccountProducts() {
        return [SELECT Id, Name, ProductCode, Family, CurrencyIsoCode, Description FROM Product2 WHERE Family = 'Account'];
    }

    public static Product2 getProductInfo(Id productId) {
        List<Product2> products = [
                SELECT Id, Name, ProductCode, CurrencyIsoCode, (
                        SELECT Id, Name, Option_Type__c, Currency_Value__c, Percent_Value__c
                        FROM Product_Options__r
                )
                FROM Product2
                WHERE Id = :productId
        ];

        return !products.isEmpty() ? products[0] : null;
    }
}